# Generated by Django 2.2.2 on 2019-11-30 18:57

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MTGSet',
            fields=[
                ('expansion_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('set_name', models.CharField(max_length=20)),
                ('set_size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MTGCard',
            fields=[
                ('SKU_ID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('color', models.CharField(choices=[('W', 'White'), ('U', 'Blue'), ('B', 'Black'), ('R', 'Red'), ('G', 'Green')], max_length=1)),
                ('card_type', models.CharField(choices=[('Artifact', 'Artifact'), ('Creature', 'Creature'), ('Enchantment', 'Enchantment'), ('Instant', 'Instant'), ('Land', 'Land'), ('Legendary', 'Legendary'), ('Planeswalker', 'Planeswalker'), ('Sorcery', 'Sorcery')], max_length=12)),
                ('converted_cost', models.IntegerField()),
                ('rule_text', models.TextField(max_length=400)),
                ('image', models.ImageField(upload_to='')),
                ('set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.MTGSet')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MTGSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DM', 'Damaged')], max_length=2)),
                ('language', models.CharField(choices=[('EN', 'English'), ('SP', 'Spanish'), ('FR', 'French'), ('DE', 'German'), ('IT', 'Italian'), ('PT', 'Portuguese'), ('JP', 'Japanese'), ('KR', 'Korean'), ('RU', 'Russian'), ('CS', 'Simplified Chinese'), ('CT', 'Traditional Chinese')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[inventory.models.validate_positive])),
                ('SKU_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.MTGCard')),
            ],
            options={
                'unique_together': {('SKU_ID', 'condition', 'language')},
            },
        ),
    ]
