# Generated by Django 2.2.2 on 2019-12-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtgcard',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
