# Generated by Django 2.2.2 on 2019-11-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtgsingle',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
