# Generated by Django 2.2.2 on 2019-12-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20191130_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtgcard',
            name='rarity',
            field=models.CharField(blank=True, choices=[('B', 'Basic'), ('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('M', 'Mythic Rare')], max_length=1),
        ),
        migrations.AlterField(
            model_name='mtgcard',
            name='card_subtype',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
