# Generated by Django 2.2.2 on 2019-12-01 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20191201_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mtgcard',
            options={'ordering': ['card_name']},
        ),
        migrations.AlterModelOptions(
            name='mtgsingle',
            options={'ordering': ['language', 'condition']},
        ),
    ]
